// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>JPetFT</b><br>
 * Generated     : <b>2018/05/11 3:18:34 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  May 11, 2018
 * @author ciplatform
 */
public abstract class JPetFTHelper extends RationalTestScript
{
	/**
	 * button_submit: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_button_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_button_submit"));
	}
	/**
	 * button_submit: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_button_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_button_submit"), anchor, flags);
	}
	
	/**
	 * button_add_to_cart: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_add_to_cart.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_add_to_cart() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_add_to_cart"));
	}
	/**
	 * button_add_to_cart: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_add_to_cart.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_add_to_cart(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_add_to_cart"), anchor, flags);
	}
	
	/**
	 * button_add_to_cart: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_add_to_cart.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_add_to_cart2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_add_to_cart2"));
	}
	/**
	 * button_add_to_cart: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_add_to_cart.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_add_to_cart2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_add_to_cart2"), anchor, flags);
	}
	
	/**
	 * button_checkout: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_checkout.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_checkout() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_checkout"));
	}
	/**
	 * button_checkout: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_checkout.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_checkout(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_checkout"), anchor, flags);
	}
	
	/**
	 * button_continue: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_continue.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_continue() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_continue"));
	}
	/**
	 * button_continue: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/button_continue.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_button_continue(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_button_continue"), anchor, flags);
	}
	
	/**
	 * sm_fish: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/sm_fish.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_sm_fish() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_sm_fish"));
	}
	/**
	 * sm_fish: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/sm_fish.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_sm_fish(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_sm_fish"), anchor, flags);
	}
	
	/**
	 * sm_reptiles: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/sm_reptiles.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_sm_reptiles() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_sm_reptiles"));
	}
	/**
	 * sm_reptiles: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://vqtools122:7979/JPetStore/images/sm_reptiles.gif
	 * 		.class : Html.IMG
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_sm_reptiles(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_sm_reptiles"), anchor, flags);
	}
	
	/**
	 * EnterMyStore: with default state.
	 *		.text : Enter my Store
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/index.shtml
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_enterMyStore() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_enterMyStore"));
	}
	/**
	 * EnterMyStore: with specific test context and state.
	 *		.text : Enter my Store
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/index.shtml
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_enterMyStore(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_enterMyStore"), anchor, flags);
	}
	
	/**
	 * EST11: with default state.
	 *		.text : EST-11
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewItem.shtml?itemId=EST-11
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_esT11() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_esT11"));
	}
	/**
	 * EST11: with specific test context and state.
	 *		.text : EST-11
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewItem.shtml?itemId=EST-11
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_esT11(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_esT11"), anchor, flags);
	}
	
	/**
	 * FISW02: with default state.
	 *		.text : FI-SW-02
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewProduct.shtml?productId=FI-SW-02
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_fisW02() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_fisW02"));
	}
	/**
	 * FISW02: with specific test context and state.
	 *		.text : FI-SW-02
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewProduct.shtml?productId=FI-SW-02
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_fisW02(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_fisW02"), anchor, flags);
	}
	
	/**
	 * RPSN01: with default state.
	 *		.text : RP-SN-01
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewProduct.shtml?productId=RP-SN-01
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_rpsN01() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rpsN01"));
	}
	/**
	 * RPSN01: with specific test context and state.
	 *		.text : RP-SN-01
	 * 		.id : 
	 * 		.href : http://vqtools122:7979/JPetStore/shop/viewProduct.shtml?productId=RP-SN-01
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_rpsN01(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rpsN01"), anchor, flags);
	}
	
	

	protected JPetFTHelper()
	{
		setScriptName("JPetFT");
	}
	
}

